In [5]:
import os
from openai import OpenAI
from src.util import read_full_paper, count_tokens
from src.gpt_extractor import PaperExtractor
from src.schema.meta_stru import NAME_FIELDS, VERIFICATION_PREFIXES, ExtractionSchema
import pandas as pd
from dotenv import load_dotenv
import json
from src.normalizers import EmbeddingNormalizer
from IPython.display import JSON
from sentence_transformers import SentenceTransformer
import pydantic 
print(pydantic.__version__)
# Load environment variables from .env
load_dotenv()

2.12.5

True

In [2]:
filepath_md = f"../data/10.1002_agj2.21621.md"
full_text = read_full_paper(filepath_md)
total_token = count_tokens(full_text)
print(f"Total Token: {total_token/1000000.0:.03f}")

Total Token: 0.011

In [3]:
client = OpenAI(api_key=os.environ["OPENAI_API_KEY"])

In [4]:
paper_extractor = PaperExtractor(
    schema=ExtractionSchema,
    client=client,
    file_unique_id='10.1002_agj2.21621',
)

In [5]:
paper_extractor.set_patch_artifacts_autosave(directory=None)

In [6]:
paper_extractor.set_document(full_text)

In [7]:
paper_extractor.get_stats()

{'extraction_runs': 0,
 'extract_turn_snapshots': 0,
 'verification_runs': 0,
 'verification_turn_snapshots': 0,
 'update_runs': 0,
 'update_turn_snapshots': 0,
 'unused_patches': 0,
 'patch_verification_results': 0,
 'patch_application_runs': 0,
 'Number of unused patches': 0,
 'Number of patch verification results': 0}

In [8]:
NAME_FIELDS

[['metadata', 'relevance'],
 ['context'],
 ['scale', 'methodology', 'tile_design'],
 ['results', 'internal_evaluation'],
 ['key_words', 'overall_synthesis']]

In [9]:
paper_extractor.cache_time

'24h'

In [10]:
paper_extractor.extract_turn(NAME_FIELDS)
paper_extractor.get_stats()

{'extraction_runs': 5,
 'extract_turn_snapshots': 1,
 'verification_runs': 0,
 'verification_turn_snapshots': 0,
 'update_runs': 0,
 'update_turn_snapshots': 0,
 'unused_patches': 0,
 'patch_verification_results': 0,
 'patch_application_runs': 0,
 'Number of unused patches': 0,
 'Number of patch verification results': 0}

In [11]:
JSON(paper_extractor.current_result.model_dump())

In [12]:
(paper_extractor.current_result.scale.category, 
 paper_extractor.current_result.tile_design.depth,
 paper_extractor.current_result.tile_design.drainage_practices
)

('Site',
 'average depth of 75 cm',
 ['Controlled Drainage', 'Conventional Drainage'])

In [13]:
paper_extractor.current_result.scale.category='Watershed'
paper_extractor.current_result.tile_design.depth = '120 cm'
# paper_extractor.current_result.tile_design.drainage_practices = ['No Drainage']

In [16]:
(paper_extractor.current_result.scale.category, 
 paper_extractor.current_result.tile_design.depth,
 paper_extractor.current_result.tile_design.drainage_practices
)

('Site', '120 cm', ['Conventional Drainage'])

In [15]:
paper_extractor.update(NAME_FIELDS)
paper_extractor.get_stats()

{'extraction_runs': 5,
 'extract_turn_snapshots': 1,
 'verification_runs': 0,
 'verification_turn_snapshots': 0,
 'update_runs': 5,
 'update_turn_snapshots': 1,
 'unused_patches': 0,
 'patch_verification_results': 0,
 'patch_application_runs': 0,
 'Number of unused patches': 0,
 'Number of patch verification results': 0}

In [17]:
(paper_extractor.current_result.scale.category, 
 paper_extractor.current_result.tile_design.depth,
 paper_extractor.current_result.tile_design.drainage_practices
)

('Site', '120 cm', ['Conventional Drainage'])

In [18]:
JSON(paper_extractor.current_result.model_dump())

In [19]:
paper_extractor.current_result.scale.category='Watershed'
paper_extractor.current_result.tile_design.depth = '120 cm'
paper_extractor.current_result.tile_design.drainage_practices = ['No Drainage']

In [20]:
(paper_extractor.current_result.scale.category, 
 paper_extractor.current_result.tile_design.depth,
 paper_extractor.current_result.tile_design.drainage_practices
)

('Watershed', '120 cm', ['No Drainage'])

In [21]:
# NEW_fields = [[
#     "/location",
#     "/metadata"
#     "/context",
#     "/scale",
#     "/methodology",
#     "/tile_design",
# ]]
verifi_field = [[
    '/scale', '/tile_design'
]]
paper_extractor.verification(NEW_fields)
paper_extractor.get_stats()

{'extraction_runs': 5,
 'extract_turn_snapshots': 1,
 'verification_runs': 1,
 'verification_turn_snapshots': 1,
 'update_runs': 5,
 'update_turn_snapshots': 1,
 'unused_patches': 3,
 'patch_verification_results': 0,
 'patch_application_runs': 0,
 'Number of unused patches': 3,
 'Number of patch verification results': 0}

In [22]:
# View proposed patches as a table

patches_data = []
for i, p in enumerate(paper_extractor.unused_patch_set.patches, 1):
    patches_data.append({
        '#': i,
        'Path': p.path,
        'Op': p.op,
        'Old': str(p.old_value)[:30],
        'New': str(p.new_value)[:30],
        # 'Confidence': f"{p.confidence:.2f}",
        'Evidence': p.evidence[:50] + '...'
    })

df_patches = pd.DataFrame(patches_data)
len(df_patches)

3

In [23]:
df_patches

,#,Path,Op,Old,New,Evidence
0,1,/scale/category,replace,Watershed,Site,"""A subsurface drainage research project was in..."
1,2,/tile_design/depth,replace,120 cm,75 cm,"""installed in spring 1983 at spacings of 5, 10..."
2,3,/tile_design/drainage_practices,append,None,Controlled Drainage,"""adaptable systems like controlled drainage ....."

In [26]:
type(paper_extractor.unused_patch_set)

patches.PatchSet

In [28]:
JSON(paper_extractor.unused_patch_set.model_dump())

In [30]:
paper_extractor.verify_patches()
paper_extractor.get_stats()

{'extraction_runs': 5,
 'extract_turn_snapshots': 1,
 'verification_runs': 1,
 'verification_turn_snapshots': 1,
 'update_runs': 5,
 'update_turn_snapshots': 1,
 'unused_patches': 0,
 'patch_verification_results': 3,
 'patch_application_runs': 0,
 'Number of unused patches': 0,
 'Number of patch verification results': 3}

In [31]:
paper_extractor.apply_verified_patches(
    literal_normalizer=EmbeddingNormalizer(),
    
)
paper_extractor.get_stats()

{'extraction_runs': 5,
 'extract_turn_snapshots': 1,
 'verification_runs': 1,
 'verification_turn_snapshots': 1,
 'update_runs': 5,
 'update_turn_snapshots': 1,
 'unused_patches': 0,
 'patch_verification_results': 0,
 'patch_application_runs': 1,
 'Number of unused patches': 0,
 'Number of patch verification results': 0}

In [35]:
(paper_extractor.current_result.scale.category, 
 paper_extractor.current_result.tile_design.depth,
 paper_extractor.current_result.tile_design.drainage_practices
)

('Site', '75 cm', ['No Drainage', 'Controlled Drainage'])

In [36]:
print('Number of extractions turns: ',len(paper_extractor.extract_turn_snapshots))
print('Number of extractions: ',len(paper_extractor.extraction_runs))
print('Number of verification turns: ',len(paper_extractor.verification_turn_snapshots))
print('Number of verification: ',len(paper_extractor.verification_runs))
print('Number of update turns: ', len(paper_extractor.update_turn_snapshots))
print('Number of applied patches: ', len(paper_extractor.patch_application_runs))

Number of extractions turns:  0
Number of extractions:  0
Number of verification turns:  0
Number of verification:  0
Number of update turns:  0
Number of applied patches:  0

In [34]:
paper_extractor.save_logs_and_clear()

PosixPath('log2')

In [ ]:
paper_extractor.

In [21]:
# with open('log2/unused_patch_set_patches.json') as f:
#     data = json.load(f)
# data

[{'op': 'replace',
  'path': '/scale/category',
  'old_value': 'Watershed',
  'new_value': 'Multiple Sites',
  'evidence': '“A subsurface drainage research project was initiated in 1983 at the Southeast Purdue Agricultural Center (SEPAC) ... The field experimental site had drains ...”'},
 {'op': 'replace',
  'path': '/scale/area_description',
  'old_value': 'Long-term field experiment at the Southeast Purdue Agricultural Center in southeastern Indiana; two blocks with three drained treatments and an undrained control.',
  'new_value': 'Long-term field experiment at the Southeast Purdue Agricultural Center in southeastern Indiana; two blocks separated by a 40-m distance.',
  'evidence': '“Each spacing was replicated in two blocks separated by a 40-m distance”'},
 {'op': 'replace',
  'path': '/tile_design/pipe_diameter',
  'old_value': '10-cm diameter',
  'new_value': '10 cm diameter',
  'evidence': '“The field experimental site had drains (10-cm diameter) installed in spring 1983”'},
 {'op': 'replace',
  'path': '/tile_design/drainage_practices',
  'old_value': ['No Drainage', 'Conventional Drainage'],
  'new_value': ['Conventional Drainage'],
  'evidence': "“the 40-m spacing plot considered to be the undrained control ... Although not truly 'undrained,' the slow permeability of the soil made this treatment much wetter than the three drained treatments”"},
 {'op': 'replace',
  'path': '/tile_design/other_practices',
  'old_value': ['no-till',
   'spring chisel tillage',
   'aerial seeding into standing soybeans near physiological maturity',
   'sidedress urea ammonium nitrate liquid',
   'liquid starter fertilizer'],
  'new_value': ['no-till',
   'spring chisel tillage',
   'aerial seeding into standing soybeans near physiological maturity',
   'sidedress urea ammonium nitrate liquid',
   'liquid starter fertilizer',
   'crop rotation'],
  'evidence': '“From 1994 onward, the plots were no-till planted, mostly in a corn-soybean rotation”'}]

In [29]:
paper_extractor.unused_patch_set = paper_extractor.unused_patch_set.model_validate({"patches": data})

In [45]:
JSON(paper_extractor.patch_verification_results[4].model_dump())

In [ ]:
from sentence_match import extract_sentence_matches, sentence_match_display
matches = extract_sentence_matches(
    context=paper_extractor.document_text,
    target_sentence=patch.evidence,
    window_size_padding=20,
    score_thr=50,
    context_words=50,
    max_results=3
)

In [25]:
sentence_match_display(
    target_sentence = patch.evidence,
    filtered_results=matches,
    max_results=2,
    score_thr=20
)

In [ ]:
df_patches

,#,Path,Op,Old,New,Evidence
0,1,/tile_design/drainage_practices,replace,['Conventional Drainage'],['Free Drainage'],"“In contrast, corn yield was significantly neg..."
1,2,/relevance/justification,replace,“Long-term crop yield benefits,“Long-term crop yield benefits,The justification field must be an exact quote...

In [17]:
import json
os.makedirs('test_log2', exist_ok=True)
open('test_log2/extract_turn.json', 'w').write(json.dumps(paper_extractor.extraction_runs, indent=2))
open('test_log2/extract_turn_snapshots.json', 'w').write(json.dumps(paper_extractor.extract_turn_snapshots, indent=2))
open('test_log2/verification_runs.json', 'w').write(json.dumps(paper_extractor.verification_runs, indent=2))
open('test_log2/verification_turn_snapshots.json', 'w').write(json.dumps(paper_extractor.verification_turn_snapshots, indent=2))

1173

In [20]:
open('test_log2/current_result.json', 'w').write(paper_extractor.current_result.model_dump_json(indent=2))

11089

In [13]:
paper_extractor.unused_patch_set

PatchSet(patches=[Patch(op='replace', path='/metadata/location/spatial_extent', old_value='A subsurface drainage research project was initiated at the Southeast Purdue Agricultural Center in southeastern Indiana.', new_value='A subsurface drainage research project was initiated in 1983 at the Southeast Purdue Agricultural Center (SEPAC) in southeastern Indiana.', evidence='"A subsurface drainage research project was initiated in 1983 at the Southeast Purdue Agricultural Center (SEPAC) in southeastern Indiana."'), Patch(op='replace', path='/relevance/justification', old_value='"evaluating the long-term (37 years) effects of subsurface tile drainage on corn and soybean yields, comparing three different drain spacings (5, 10, and 20 m) to an undrained control"', new_value='"evaluating the long-term (37 years) effects of subsurface tile drainage on corn and soybean yields, comparing three different drain spacings (5, 10, and 20 m) to an undrained control"', evidence='"evaluating the long-term (37 years) effects of subsurface tile drainage on corn and soybean yields, comparing three different drain spacings (5, 10, and 20 m) to an undrained control"'), Patch(op='replace', path='/context/scientific_question', old_value='How did varying subsurface drainage spacings affect long-term crop yields compared to an undrained control, and how were these effects influenced by rainfall at different periods of the growing season?', new_value='How did varying subsurface drainage spacings affect long-term crop yields compared to an undrained control, and how were these effects influenced by precipitation patterns of certain periods of the growing season?', evidence='"no research has yet investigated the potential impact of varying drain spacing on long-term crop productivity and how these effects might be affected by precipitation of certain periods of the growing season."'), Patch(op='replace', path='/context/research_gap', old_value='Long-term yield benefits of drainage, particularly with varying spacings, in an ever-changing climate are largely unknown; no research had yet investigated the potential impact of varying drain spacing on long-term crop productivity and how these effects might be affected by precipitation of certain periods of the growing season.', new_value='Long-term yield benefits of drainage, particularly with varying spacings, in an ever-changing climate are largely unknown.', evidence='"long-term yield benefits of drainage, particularly with varying spacings, in an ever-changing climate are largely unknown."'), Patch(op='replace', path='/context/objectives', old_value='To assess how drainage spacings of 5, 10, and 20 m impacted corn and soybean yields compared to an undrained control in a long-term trial started in 1984, and to evaluate how these effects were influenced by rainfall before planting, after planting, and between planting and harvest.', new_value='To assess how drainage spacings of 5, 10, and 20 m impacted corn and soybean yields compared to an undrained control in a long-term trial (started in 1984) in southeastern Indiana and how these effects were influenced by the amount of rainfall of specific periods of the growing season.', evidence='"The goals of this study were to assess how various drainage spacings (5, 10, and 20m ) impacted crop yields compared to the undrained control in a long-term trial (started in 1984) in southeastern Indiana and how these effects were influenced by the amount of rainfall of specific periods of the growing season."'), Patch(op='replace', path='/context/hypotheses', old_value=['crop yields would demonstrate a steady increase over the 37-year period, particularly in the tile-drained treatments', 'narrow spacing (e.g., 5 m) of drainage treatments would outperform wider spacing due to their greater drainage efficiency', 'drainage spacing treatment would affect crop yield response to rainfall differently at different phases of the growing season'], new_value=['crop yields would demonstrate a steady increase over the 37-year period, particularly in the tile-drained treatments', 'narrow spacing (e.g., 5m ) of drainage treatments would outperform wider spacing due to their greater drainage efficiency', 'drainage spacing treatment would affect crop yield response to rainfall differently at different phases of the growing season'], evidence='"As a result, we hypothesized that (1) crop yields would demonstrate a steady increase over the 37-year period, particularly in the tile-drained treatments; (2) narrow spacing (e.g., 5m ) of drainage treatments would outperform wider spacing due to their greater drainage efficiency; and (3) drainage spacing treatment would affect crop yield response to rainfall differently at different phases of the growing season."'), Patch(op='replace', path='/scale/category', old_value='Single Plot', new_value='Multiple Sites', evidence='"Two replicates, or blocks, were measured per year" and the experiment included "three drained treatments and an undrained control" across the field trial, indicating more than a single plot.'), Patch(op='replace', path='/methodology/approach_types', old_value=['Observational'], new_value=['Observational', 'Experimental'], evidence='"A subsurface drainage research project was initiated in 1983" and "The field experimental site had drains ... installed in spring 1983 at spacings of 5, 10, and 20 m"'), Patch(op='add', path='/tile_design/drainage_coefficient', old_value=None, new_value='not stated', evidence='No drainage coefficient is given in the paper.'), Patch(op='replace', path='/tile_design/drainage_practices', old_value=['Free Drainage'], new_value=['Free Drainage'], evidence='"the 40-m spacing plot considered to be the undrained control" and comparisons are made to "tile-drained treatments" without controlled drainage structures.'), Patch(op='replace', path='/results/quantitative_stats/0/value', old_value='12% - 17%', new_value='16.8%, 13.3%, and 12.4%', evidence='"Over the 24 corn-growing years from 1984 to 2020, yields were higher for the 5, 10, and 20 m drainage spacings by 16.8%, 13.3%, and 12.4%, respectively, compared to the undrained control."'), Patch(op='replace', path='/results/quantitative_stats/0/context', old_value='Drainage treatments compared to the control in the abstract', new_value='Over the 24 corn-growing years from 1984 to 2020', evidence='"Over the 24 corn-growing years from 1984 to 2020, yields were higher for the 5, 10, and 20 m drainage spacings by 16.8%, 13.3%, and 12.4%, respectively, compared to the undrained control."'), Patch(op='replace', path='/results/summary_bullets/4', old_value='Post-planting rainfall was negatively related to yields, especially for corn in the undrained control, and drainage spacing partially mitigated this negative effect.', new_value='Post-planting rainfall was negatively related to yields, especially for corn in the undrained control, and drainage spacing partially mitigated this negative effect; in the first 10 years, post-planting rain decreased yield in the undrained control and 20 m spacing, while in the most recent 10 years it also tended to decrease yield in 10 m spacing.', evidence='"For the first 10 years of corn data, post-planting rain decreased yield in the undrained control ... and the 20 m drainage spacing treatment ... The 10 m spacing also tended toward decreased yield ... For the most recent 10 years of corn planting, post-planting rain also decreased yield in the undrained control ... and 20 m spacing ... The 10 m spacing also tended toward decreased yield"'), Patch(op='replace', path='/results/summary_bullets/5', old_value='Growing-season rainfall was positively related to corn yield in the drained systems, especially at 5 m spacing.', new_value='Growing-season rainfall was positively related to corn yield in the drained systems, especially at 5 m spacing; no significant effect of growing season rainfall on corn yield was found for either 10-year period.', evidence='"Our findings show a positive correlation between corn yields and growing season (plant-to-harvest) rainfall in the drained systems, especially in the narrowest spacing drainage treatment (5 m)." and "There was no significant effect of growing season (plant-to-harvest) rainfall on corn yield for either 10-year period"'), Patch(op='replace', path='/internal_evaluation/limitations/0', old_value='With a small number of replicates within year, this study has limited power to distinguish small differences between drainage treatments and subtle changes between years.', new_value='With a small number of replicates within year, this study has limited power to distinguish small differences between drainage treatments and subtle changes between years; several pairwise comparisons could not be estimated because of the included rain covariates.', evidence='"With a small number of replicates within year, this study has limited power to distinguish small differences between drainage treatments and subtle changes between years." and "Several pairwise comparisons could not be estimated because of the included rain covariates"'), Patch(op='replace', path='/overall_synthesis/main_contribution', old_value='The study shows that long-term subsurface tile drainage increased corn yields on poorly drained soils, with stronger benefits in later years and under narrower drain spacing, while soybean yields were not affected.', new_value='The study shows that long-term subsurface tile drainage increased corn yields on poorly drained soils, with stronger benefits in later years and under narrower drain spacing, while soybean yields were not affected; rainfall 14 days postplanting was inversely related to yields, and growing-season precipitation was beneficial in drained treatments.', evidence='"The inverse relationship between corn yields and rainfall 14 days postplanting, coupled with the positive relationship between corn yields and growing-season precipitation for the drained treatments"'), Patch(op='replace', path='/overall_synthesis/executive_summary', old_value='Using a 37-year field trial in southeastern Indiana, the authors compared corn and soybean yields under three subsurface drain spacings and an undrained control, and related yield patterns to rainfall timing. Corn yields were significantly higher in all drained treatments and became more responsive over time, whereas soybean yields showed no drainage effect; rainfall 14 days after planting was detrimental to yields, especially where drainage was absent or less efficient.', new_value='Using a 37-year field trial in southeastern Indiana, the authors compared corn and soybean yields under three subsurface drain spacings and an undrained control, and related yield patterns to rainfall timing. Corn yields were significantly higher in all drained treatments and became more responsive over time, whereas soybean yields showed no drainage effect. Rainfall 14 days after planting was detrimental to yields, especially where drainage was absent or less efficient, while growing-season rainfall benefited corn in the drained systems.', evidence='"Corn yields were significantly higher in all three drained treatments than in the undrained control"; "Soybean yields were unaffected by drainage treatment"; "The inverse relationship between corn yields and rainfall 14 days postplanting, coupled with the positive relationship between corn yields and growing-season precipitation for the drained treatments"')])

In [15]:
import json
os.makedirs('test_log', exist_ok=True)
open('test_log/test_extract_turn.json', 'w').write(json.dumps(paper_extractor.extraction_runs, indent=2))
open('test_log/test_extract_turn_snapshots.json', 'w').write(json.dumps(paper_extractor.extract_turn_snapshots, indent=2))

14836

In [ ]:
extraction_schema = meta_stru_v2.ExtractionSchema
extraction_schema.

In [ ]:
SECTION_GUIDANCE: Dict[str, str] = {
    "metadata": "Extract bibliographic metadata and location details exactly as stated.",
    "relevance": "Extract only relevance level, whether tile drainage is primary, and one short justification.",
    "key_words": "Extract 10-15 high-level keywords/concepts. If absent, use '-9999'.",
    "context": "Extract scientific question, gap, objectives, and explicitly stated hypotheses.",
    "scale": "Extract study scale and area/site metrics exactly as stated.",
    "methodology": "Extract study duration, methodology types, models, and methods.",
    "tile_design": "Extract tile design/practice configuration and related agronomic details.",
    "results": "Extract explicit findings and key quantitative statistics only.",
    "internal_evaluation": "Extract achievements, limitations, and future directions stated by authors.",
    "overall_synthesis": "Extract high-level contribution and concise executive summary grounded in text.",
}

In [ ]:

ROLE = "High-precision data extraction engine specialized in agricultural hydrology and subsurface (tile) drainage."

CORE_RULES = """
CRITICAL RULES:

1. DOMAIN:
All references to "tile" refer strictly to agricultural subsurface drainage systems.

2. STRICT GROUNDING:
- Use ONLY information explicitly stated in the paper.
- If information is not explicitly stated → return null.
- Do NOT infer, assume, generalize, or use external knowledge.

3. FIDELITY:
- Preserve exact numerical values and units.
- Preserve author wording for qualitative findings when possible.

4. STRUCTURE:
- Output must strictly follow the provided schema.
- Do NOT add extra fields.
- Do NOT change field names or hierarchy.

5. KEYWORDS:
- Extract high-level scientific themes only.
- Do NOT include:
  - numbers
  - specific chemicals
  - local/place names
"""

SYSTEM_PROMPT = f"""
{ROLE}

You extract or verify structured information from scientific papers.

{CORE_RULES}
"""


# -----------------------------
# EXTRACTION TASK
# -----------------------------

EXTRACTION_TASK = """
TASK:

Extract structured information from the paper.

- Populate ONLY fields supported by explicit text.
- Leave missing fields as null or empty.
- Do NOT hallucinate.
"""


# -----------------------------
# VERIFICATION TASK (PATCH MODE)
# -----------------------------

VERIFICATION_TASK = """
TASK: Verification (Patch Mode)

You are given:
1. The original paper text
2. A previous extraction result

Your job is to produce a PatchSet that corrects errors.

INSTRUCTIONS:

1. ONLY fill patch_set, and leave other fields empty.

2. Each patch must be atomic and minimal.

3. WHEN TO PATCH:
- Only if explicitly contradicted by source text
- Or clearly missing but explicitly present in text

4. PATCH RULES:
- Use "replace" for correcting existing values
- Use "add" for missing fields
- Use "append" for adding list elements
- Do NOT simulate replace using remove+append

5. EVIDENCE:
- Each patch MUST include a supporting quote or near-verbatim paraphrase

6. CONFIDENCE:
- Only include patches with high confidence (>= 0.8 recommended)

7. CONSERVATISM:
- If unsure → DO NOT PATCH
"""


# -----------------------------
# USER PROMPT BUILDER
# -----------------------------

def build_user_prompt(
    full_text: str,
    focus_area: list[str] | None = None,
    verification: bool = False,
    previous_extraction: ExtractionSchema | None = None,
) -> str:

    prefix = (
        "Paper content follows. Treat this as the ONLY source of truth.\n\n"
        "=== PAPER START ===\n"
        f"{full_text}\n"
        "=== PAPER END ===\n"
    )

    if verification:
        prompt = prefix + "\n\n"

        prompt += "PREVIOUS EXTRACTION:\n"
        prompt += json.dumps(
            previous_extraction.model_dump(exclude_none=True),
            indent=2,
        )
        prompt += "\n\n"

        prompt += VERIFICATION_TASK

        if focus_area:
            prompt += (
                "\n\nFOCUS CONSTRAINT:\n"
                f"Only verify and patch the following sections: {', '.join(focus_area)}.\n"
                "Ignore all other fields."
            )

    else:
        prompt = prefix + "\n\n" + EXTRACTION_TASK

        if focus_area:
            prompt += (
                "\n\nFOCUS CONSTRAINT:\n"
                f"Only extract the following sections: {', '.join(focus_area)}.\n"
                "Leave all other fields empty."
            )
        else:
            prompt += (
                "\n\nExtract all fields defined in the schema "
                "(except patch_set)."
            )

    return prompt

SyntaxError: unterminated string literal (detected at line 2) (657742527.py, line 2)

In [ ]:


user_prompt = f"Your are "

# Prepare messages
messages = [
    {"role": "system", "content": system_prompt},
    {"role": "user", "content": f"Paper content follows. Treat this as the only source of truth: {full_text}"},
    {"role": "user", "content": user_prompt}
]

In [ ]:
resp1 = client.responses.create(
    model=MODEL,
    input=[
        {
            "role": "developer",
            "content": [{"type": "input_text", "text": developer_instruction}]
        },
        {
            "role": "user",
            "content": [
                {
                    "type": "input_text",
                    "text": "Extract the paper metadata and study context."
                },
                {
                    "type": "input_file",
                    "file_id": paper_file.id
                }
            ]
        }
    ],
    text={
        "format": {
            "type": "json_schema",
            "name": metadata_context_schema["name"],
            "schema": metadata_context_schema["schema"],
            "strict": True
        }
    }
)

test

In [4]:
import os
import json
import time
import hashlib
import sqlite3
from typing import Optional, Dict, Any

from openai import OpenAI

client = OpenAI(api_key=os.environ["OPENAI_API_KEY"])
MODEL = os.environ.get("OPENAI_MODEL", "gpt-5-mini")  # change if needed


# -----------------------------
# 1) Simple SQLite cache
# -----------------------------
DB_PATH = "paper_extraction_cache.db"

def init_db():
    conn = sqlite3.connect(DB_PATH)
    conn.execute("""
        CREATE TABLE IF NOT EXISTS extractions (
            doc_hash TEXT PRIMARY KEY,
            source_id TEXT,
            schema_version TEXT,
            result_json TEXT NOT NULL,
            created_at REAL NOT NULL
        )
    """)
    conn.commit()
    conn.close()

def get_cached_result(doc_hash: str) -> Optional[Dict[str, Any]]:
    conn = sqlite3.connect(DB_PATH)
    cur = conn.execute(
        "SELECT result_json FROM extractions WHERE doc_hash = ?",
        (doc_hash,)
    )
    row = cur.fetchone()
    conn.close()
    if row:
        return json.loads(row[0])
    return None

def put_cached_result(doc_hash: str, source_id: str, schema_version: str, result: Dict[str, Any]):
    conn = sqlite3.connect(DB_PATH)
    conn.execute("""
        INSERT OR REPLACE INTO extractions (doc_hash, source_id, schema_version, result_json, created_at)
        VALUES (?, ?, ?, ?, ?)
    """, (
        doc_hash,
        source_id,
        schema_version,
        json.dumps(result, ensure_ascii=False),
        time.time()
    ))
    conn.commit()
    conn.close()


# -----------------------------
# 2) Utilities
# -----------------------------
def normalize_text(text: str) -> str:
    return " ".join(text.split())

def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


# -----------------------------
# 3) JSON schema for extraction
# -----------------------------
SCHEMA_VERSION = "v1"

PAPER_SCHEMA = {
    "name": "paper_metadata_extraction",
    "strict": True,
    "schema": {
        "type": "object",
        "properties": {
            "title": {"type": ["string", "null"]},
            "authors": {
                "type": ["array", "null"],
                "items": {"type": "string"}
            },
            "journal": {"type": ["string", "null"]},
            "year": {"type": ["integer", "null"]},
            "doi": {"type": ["string", "null"]},
            "study_area": {"type": ["string", "null"]},
            "methods_summary": {"type": ["string", "null"]},
            "main_findings": {
                "type": ["array", "null"],
                "items": {"type": "string"}
            }
        },
        "required": [
            "title",
            "authors",
            "journal",
            "year",
            "doi",
            "study_area",
            "methods_summary",
            "main_findings"
        ],
        "additionalProperties": False
    }
}

DEVELOPER_INSTRUCTIONS = """
You extract metadata from scientific literature.

Rules:
- Extract only information explicitly stated in the provided text.
- Do not infer missing values.
- If a field is not explicitly available, return null.
- Return all required keys.
- Keep summaries concise and grounded in the text.
"""


# -----------------------------
# 4) Extraction function
# -----------------------------
def extract_single_paper(source_id: str, paper_text: str) -> Dict[str, Any]:
    normalized = normalize_text(paper_text)
    doc_hash = sha256_text(normalized)

    cached = get_cached_result(doc_hash)
    if cached is not None:
        print(f"[CACHE HIT] source_id={source_id}")
        return cached

    print(f"[CACHE MISS] source_id={source_id}")

    response = client.chat.completions.create(
        model=MODEL,
        messages=[
            {"role": "developer", "content": DEVELOPER_INSTRUCTIONS},
            {
                "role": "user",
                "content": f"Extract the metadata from this paper text:\n\n{normalized}"
            }
        ],
        response_format={
            "type": "json_schema",
            "json_schema": PAPER_SCHEMA
        },

        # OpenAI prompt caching knobs
        prompt_cache_key=f"paper_extract:{SCHEMA_VERSION}",
        prompt_cache_retention="24h"
    )

    content = response.choices[0].message.content
    result = json.loads(content)

    put_cached_result(
        doc_hash=doc_hash,
        source_id=source_id,
        schema_version=SCHEMA_VERSION,
        result=result
    )

    # Optional: inspect token usage if returned by your SDK/version
    usage = getattr(response, "usage", None)
    if usage is not None:
        print("[USAGE]", usage)

    return result


if __name__ == "__main__":
    init_db()

    paper_id = "paper_001"
    paper_text = """
    Title: Example Hydrology Paper
    Authors: Alice Smith; Bob Lee
    Journal: Water Resources Research
    Year: 2024
    DOI: 10.1234/example-doi

    This study evaluates streamflow response in a tile-drained watershed in Illinois.
    Methods include field monitoring and model simulation.
    Main findings show that drainage altered seasonal runoff timing.
    """

    result1 = extract_single_paper(paper_id, paper_text)
    print(json.dumps(result1, indent=2, ensure_ascii=False))

    # Second call reuses your local cache
    result2 = extract_single_paper(paper_id, paper_text)
    print(json.dumps(result2, indent=2, ensure_ascii=False))

[CACHE HIT] source_id=paper_001
{
  "title": "Example Hydrology Paper",
  "authors": [
    "Alice Smith",
    "Bob Lee"
  ],
  "journal": "Water Resources Research",
  "year": 2024,
  "doi": "10.1234/example-doi",
  "study_area": "tile-drained watershed in Illinois",
  "methods_summary": "Field monitoring and model simulation.",
  "main_findings": [
    "Drainage altered seasonal runoff timing."
  ]
}
[CACHE HIT] source_id=paper_001
{
  "title": "Example Hydrology Paper",
  "authors": [
    "Alice Smith",
    "Bob Lee"
  ],
  "journal": "Water Resources Research",
  "year": 2024,
  "doi": "10.1234/example-doi",
  "study_area": "tile-drained watershed in Illinois",
  "methods_summary": "Field monitoring and model simulation.",
  "main_findings": [
    "Drainage altered seasonal runoff timing."
  ]
}

## test

In [4]:
from openai import OpenAI
import os
import json
import time
import hashlib
import sqlite3
from typing import Optional, Dict, Any

In [5]:
os.environ["OPENAI_API_KEY"]

'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'

In [1]:
from patches import Patch, PatchSet

def create_patch_set(unused_patch_set: PatchSet = PatchSet()):
    return unused_patch_set

test_patch_set = create_patch_set()

In [ ]:
if test_patch_set.patches:
    print(test_patch_set.patches)
else:
    print("No patches to verify")

No patches to verify

In [5]:
len(test_patch_set.patches)

0